server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      #discovery:
        #locator:
          #enabled: true
          #lower-case-service-id: true
      routes:
      - id: user-status-check
        uri: lb://user-ws
        predicates:
        - Path=/user-ws/user/status/check
        - Method=GET
        - Header=Authorization, Bearer (.*)
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
        #- AuthorizationHeaderFilter
      - id: user-ws-register
        uri: lb://user-ws
        predicates:
          - Path=/user-ws/user/register
          - Method=POST
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
      - id: user-ws-h2-console
        uri: lb://user-ws
        predicates:
          - Path=/user-ws/h2-console
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
      - id: user-ws-login
        uri: lb://user-ws
        predicates:
          - Path=/user-ws/user/login
          - Method=POST
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
