server:
  port: 8082
token:
  secret: dgjorufhrsnjdu438fkdj38fdmcv7dm3ckvhrsnjjuwelueivhe848fhedldh5ndk
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      #discovery:
        #locator:
          #enabled: true
          #lower-case-service-id: true
      routes:
      # Microservice status check routes START
      - id: user-status-check
        uri: lb://user-ws
        predicates:
        - Path=/user-ws/user/status/check
        - Method=GET
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
      - id: product-status-check
        uri: lb://product-ws
        predicates:
          - Path=/product-ws/product/status/check
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/product-ws/(?<segment>.*), /$\{segment}
      - id: file-upload-status-check
        uri: lb://file-upload-ws
        predicates:
          - Path=/file-upload-ws/file/status/check
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/file-upload-ws/(?<segment>.*), /$\{segment}
      # Microservice status check routes END
      - id: user-ws-register
        uri: lb://user-ws
        predicates:
          - Path=/user-ws/user/register
          - Method=POST
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
      - id: product-ws-create
        uri: lb://product-ws
        predicates:
          - Path=/product-ws/product/create
          - Method=POST
          #- Header=Authorization, Bearer (.*)
        filters:
          - RemoveRequestHeader=Cookie
          #- AuthorizationHeaderFilter=ROLE_ADMIN
          - RewritePath=/product-ws/(?<segment>.*), /$\{segment}
      - id: file-upload-ws
        uri: lb://file-upload-ws
        predicates:
          - Path=/file-upload-ws/file/**
          - Method=GET,POST
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/file-upload-ws/(?<segment>.*), /$\{segment}
      # H2 console routes START
      - id: user-ws-h2-console
        uri: lb://user-ws
        predicates:
          - Path=/user-ws/h2-console
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
      - id: product-ws-h2-console
        uri: lb://product-ws
        predicates:
          - Path=/product-ws/h2-console
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/product-ws/(?<segment>.*), /$\{segment}
      - id: file-upload-ws-h2-console
        uri: lb://file-upload-ws
        predicates:
          - Path=/file-upload-ws/h2-console
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/file-upload-ws/(?<segment>.*), /$\{segment}
      # H2 console routes END
      - id: user-ws-login
        uri: lb://user-ws
        predicates:
          - Path=/user-ws/user/login
          - Method=POST
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/user-ws/(?<segment>.*), /$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
